# Generated by Django 4.1.3 on 2022-11-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("number", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("capacity", models.SmallIntegerField()),
                ("numberOfBeds", models.SmallIntegerField()),
                (
                    "roomType",
                    models.CharField(
                        choices=[("Forest Face", "FF"), ("River Face", "RF")],
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField()),
                ("statusStartDate", models.DateTimeField(null=True)),
                ("statusEndDate", models.DateTimeField(null=True)),
            ],
            options={
                "verbose_name_plural": "Room",
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.guest",
                    ),
                ),
                (
                    "roomNumber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room.room",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Booking",
                "db_table": "booking",
            },
        ),
    ]
