# Generated by Django 4.1.3 on 2022-12-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="roomType",
            field=models.CharField(
                choices=[("FF", "Forest Face"), ("RF", "River Face")], max_length=20
            ),
        ),
    ]
