# Generated by Django 4.1.3 on 2022-12-02 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_alter_room_roomtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="numberOfBeds",
            new_name="number_of_beds",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="roomType",
            new_name="room_type",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="statusEndDate",
            new_name="status_end_date",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="statusStartDate",
            new_name="status_start_date",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
